Fix #9 and Large Refactor
jgchristopher/obsidian-clipper pull request #10
Opened 2023-02-17 02:32 UTC by jgchristopher

- #9 support. I had to not allow '#' Level 1 headers in clipped content but appending and prepending now works
- Large Refactor of the codebase to make it easier to move forward
- Use Svelte for settings configuration

2023-02-17 02:33 UTC, jgchristopher commented on README.md
> +Obsidian Clipper can be configured to write to either the a daily note, weekly note, or both. I have plans to allow other locations.
Rewrite this sentence.

2023-02-17 02:34 UTC, jgchristopher commented on src/main.ts
> +    //const { subscribe, set, update } = writable(this.plugin.settings);
remove commented out code

2023-02-17 02:36 UTC, jgchristopher commented on src/periodicnotes/filewriter.ts
> +                cachedHeading.heading === heading &&
Just return this and get rid of the if/else

2023-02-17 02:37 UTC, jgchristopher commented on src/settings/BookmarkletSettingsGroup.svelte
> +	import { BookmarketlGenerator } from "src/bookmarkletgenerator";
format

2023-02-18 18:22 UTC, nicknisi requested changes
Looks great overall! It might be worthwhile to setup Prettier and eslint to help prevent most of the nitpicks I had!

2023-02-18 18:22 UTC, nicknisi commented on src/periodicnotes/periodicnoteentry.ts
> +    let now = window.moment();
```suggestion
    const now = window.moment();
```

2023-02-18 18:22 UTC, nicknisi commented on src/periodicnotes/periodicnoteentry.ts
> +    let now = window.moment();
**question:** Is there a reason you're getting at `moment` from `window`? Could it be imported instead?

2023-02-18 18:22 UTC, nicknisi commented on src/periodicnotes/periodicnoteentry.ts
> +    let now = window.moment();
as a follow-up, if `window` is the proper place, then maybe replace it with `globalThis`

```suggestion
    const now = globalThis.moment();
```

2023-02-18 18:22 UTC, nicknisi commented on src/periodicnotes/sectionposition.ts
> +	typeof SectionPosition[keyof typeof SectionPosition];
**issue:** The type here is just `string` when I think you mean for it to be `'prepend' | 'append'`.

```suggestion
export type SectionPosition = 'prepend' | 'append';
```

2023-02-18 18:22 UTC, nicknisi commented on src/periodicnotes/sectionposition.ts
> +	typeof SectionPosition[keyof typeof SectionPosition];
Another suggestion: you might be able to get away without the object literal and just relying on string comparison. With this type, you'll have the same amount of type safety.

2023-02-18 18:22 UTC, nicknisi commented on src/periodicnotes/weeklyperiodicnoteentry.ts
> +    let weeklyNote = await createWeeklyNote(moment);
```suggestion
    const weeklyNote = await createWeeklyNote(moment);
```

2023-02-18 18:22 UTC, nicknisi commented on src/settings/CommonSettingsGroup.svelte
> +<div class="clp_section_margin">
**nitpick:** This file looks like it's tabs and others are spaces. Maybe set up editorconfig or prettier.

2023-02-18 18:22 UTC, nicknisi commented on src/settings/settingsstore.ts
> +import { type Writable, writable } from "svelte/store";
**praise:** whoa, til about `import { type ... }` 😱

2023-02-18 18:22 UTC, nicknisi commented on tsconfig.json
> +	  "strictNullChecks": true,
**nitpick:** stray tab
```suggestion
      "strictNullChecks": true,
```

2023-02-19 03:21 UTC, jgchristopher commented on src/periodicnotes/sectionposition.ts
> +	typeof SectionPosition[keyof typeof SectionPosition];
I was missing an `as const` after the SectionPosition object literal. Adding that gave the intended behavior.

2023-02-19 03:48 UTC, jgchristopher commented on src/periodicnotes/filewriter.ts
> +      let insertSection: { firstLine: number; lastLine?: number } = {
This is working but I need to look at this code more and simplify

2023-02-19 04:08 UTC, merged